[workspace]
resolver = "2"

members = [ 
    "tracing-tape",
    "tracing-tape-recorder",
    "tracing-tape-parser",
    "trace-deck",
]

[profile.release]
# lto = true
panic = "abort"

[workspace.dependencies]
tracing = "0.1.40"
criterion = { version = "0.5", features = ["html_reports"] }
