[package]
name = "tracing-tape-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = "0.7.35"
tracing-tape = { path = "../tracing-tape" }
ahash = "0.8.11"
smallvec = "1.13.2"
petgraph = "0.6.5"
tracing.workspace = true
