name: Build

on:
  push:
    # branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  trunk-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cargo-bins/cargo-binstall@main
    - name: Install Trunk
      run: cargo binstall trunk
    - name: Build
      run: trunk build
      working-directory: ./trace-deck
